FROM ubuntu

EXPOSE 80
#EXPOSE 80/UPD
#EXPOSE 80/TCP

MAINTAINER yashk5635@gmail.com
WORKDIR /var/www/html
RUN apt-get update
RUN apt-get install -y postgresql
#CMD apt-get install nginx
COPY index.html ./

#RUN groupadd -r test0 && useradd -r -g test0 test0
#USER test0
#ENTRYPOINT echo "my container"
#RUN apt-get clean
#CMD ["echo", "Image created"]

#sudo docker image inspect --format='' 

