services:
  block-33-floor1: #NAME OF OUR CONTAINER OR SERVICE.
    image: busybox:latest
    tty: true # IT IS USED TO TELL DOCKER, AFTER CREATION OF CONTAINER LET THEM RUN IN BACKGROUND, USER WILL CONNECT IT AFTER SOME TIME.
    networks:
      - block33-net
      
  block-33-floor2:
    image: busybox:latest
    tty: true
    networks:
      - block33-net
      
  block-33-floor3:
    image: busybox:latest
    tty: true
    networks:
      - block33-net
      
#BLOCK 34 INFROMATION STARTING FROM HERE.
  block-34-floor1:
    image: busybox:latest
    tty: true
    networks:
      - block34-net
      
  block-34-floor2:
    image: busybox:latest
    tty: true
    networks:
      - block34-net
      
  block-34-floor3:
    image: busybox:latest
    tty: true
    networks:
      - block34-net
      

networks:
  block33-net: # NAME OF OUR NETWORK, WHICH WILL BE CREATED
    driver: bridge
  block34-net: # NAME OF OUR NETWORK, WHICH WILL BE CREATED
    driver: bridge

# TO KNOW THE IP-ADDRESS OF THESE NEWLY CREATED CONTAINER DO "NETWORK INSPECT".
# REMEMBER TO USE --help OPTION IN CLI